substitutions:
  _BACKEND_URL: http://34.116.75.106:8000

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-backend
    args:
      - build
      - -t
      - fuelspy-backend:$SHORT_SHA
      - ./backend

  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_BACKEND_URL}
      - -t
      - fuelspy-frontend:$SHORT_SHA
      - ./frontend

options:
  logging: NONE
